<?php

namespace Acme\ShopBundle\Repository;

use Acme\ShopBundle\Base\MainRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends MainRepository
{
}
