<?php

namespace Acme\ShopBundle\Repository;

use Acme\ShopBundle\Base\MainRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends MainRepository
{
}
