services:
    restaurant.user_change_listener:
        class: Acme\ShopBundle\EventListener\UserChangeEventListener
        tags:
            - { name: kernel.event_listener, event: user_change, method: userChange }
        arguments:
            - @service_container
